[package]
name = "traefikctl"
version = "0.1.22"
edition = "2021"
repository = "https://github.com/auser/traefikctl"
description = "A CLI for managing traefik with etcd (and more)"
homepage = "https://github.com/auser/traefikctl"
authors = ["Ari <me@ari.io>"]
license = "Apache-2.0 or MIT"

[[bin]]
name = "traefikctl"
path = "src/main.rs"

[package.metadata.wix]
upgrade-guid = "F4761C69-4FF9-4810-AF9E-2AF110D7CF42"
path-guid = "28239E20-C62B-43AD-BC64-61911768BEF6"
license = false
eula = false


[features]
default = ["config", "etcd", "log", "cli"]
cli = ["dep:clap"]
config = [
  "dep:async-trait",
  "dep:config",
  "dep:tracing",
  "dep:serde_json",
  "dep:serde_yaml",
]
etcd = ["dep:etcd-client", "dep:tokio", "dep:tracing"]
log = [
  "dep:chrono",
  "dep:time",
  "dep:tracing",
  "dep:tracing-appender",
  "dep:tracing-subscriber",
]
restful = [
  "dep:axum",
  "dep:axum-extra",
  "dep:serde_json",
  "dep:tokio",
  "dep:tracing",
  "dep:reqwest",
]

[dependencies]
async-trait = { version = "0.1.83", optional = true }
axum = { version = "0.7.7", optional = true }
axum-extra = { version = "0.9.4", optional = true }
chrono = { version = "0.4.38", features = ["serde"], optional = true }
clap = { version = "4.5.20", features = ["derive", "env"], optional = true }
color-eyre = "0.6.3"
colored = "2.1.0"
config = { version = "0.14.1", optional = true }
convert_case = "0.6.0"
etcd-client = { version = "0.14.0", features = [
  "tls",
  "tls-roots",
], optional = true }
ordermap = { version = "0.5.3", features = ["serde"] }
reqwest = { version = "0.12.9", optional = true }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = { version = "1.0.132", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
thiserror = "2.0.0"
time = { version = "0.3.36", optional = true }
tokio = { version = "1.41.1", features = ["full"], optional = true }
tracing = { version = "0.1.40", optional = true }
tracing-appender = { version = "0.2.3", optional = true }
tracing-subscriber = { version = "0.3.18", features = [
  "env-filter",
  "local-time",
], optional = true }
url = "2.5.3"

[build-dependencies]
protoc = "2.28.0"
cargo-dist = "0.25.1"

[dev-dependencies]
pretty_assertions = "1.4"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
