[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# CI backends to support
ci = "github"
# A GitHub repo to push Homebrew formulas to
tap = "auser/homebrew-tap"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.25.1"
github-build-setup = "../build-setup.yml"
