[tasks.watch-backend]
command = "cargo"
args = ["run", "--", "serve", "-l", "debug"]
watch = { watch = ["./src/", "./bin/"] }
workspace = false

[tasks.watch-frontend]
command = "pnpm"
cwd = "./frontend"
args = ["run", "dev", "--host"]
watch = { watch = ["./frontend/"] }
workspace = false

[tasks.install-frontend-deps]
command = "pnpm"
cwd = "./frontend"
args = ["install", "--force"]
workspace = false

[tasks.build-frontend]
command = "pnpm"
cwd = "./frontend"
args = ["run", "build"]
workspace = false

[tasks.dev]
run_task = { name = ["watch-backend", "watch-frontend"], parallel = true }

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
workspace = false
dependencies = ["build-frontend"]

[tasks.release]
command = "cargo"
args = ["release", "--execute", "--no-confirm", "--allow-dirty"]
workspace = false
dependencies = ["build-frontend"]
