[tasks.watch-backend]
command = "cargo"
args = ["run", "--", "serve", "-l", "debug"]
watch = { watch = ["./src/", "./bin/"] }
workspace = false

[tasks.watch-frontend]
command = "pnpm"
cwd = "./frontend"
args = ["run", "dev", "--host"]
watch = { watch = ["./frontend/"] }
workspace = false

[tasks.build-frontend]
command = "pnpm"
cwd = "./frontend"
args = ["run", "build"]
workspace = false

[tasks.dev]
run_task = { name = ["watch-backend", "watch-frontend"], parallel = true }
