[tasks.watch-frontend]
cwd = "./frontend"
command = "npm"
args = ["run", "dev"]

[tasks.watch-server]
command = "cargo"
cwd = "."
args = ["watch", "-w", "src", "-x", "run", "--", "serve"]

[tasks.dev]
run_task = [{ name = ["watch-frontend", "watch-server"] }]

[tasks.build]
command = "cargo"
cwd = "."
args = ["build"]

[tasks.typeshare-ts]
command = "typeshare"
cwd = "."
args = [
  "--lang",
  "typescript",
  "--output-file=frontend/src/types/traefik.ts",
  "./src",
]
