etcd:
  endpoints: ["https://0.0.0.0:2379"]
  timeout: 2000
  keep_alive: 300
  tls:
    cert: "./config/tls/etcd-peer.pem"
    key: "./config/tls/etcd-peer-key.pem"
    ca: "./config/tls/ca.pem"
    domain: ari.io

middlewares:
  headers:
    additional_headers:
      frameDeny: true

  templated_headers:
    headers:
      custom_request_headers:
        ServiceAddr: "{{ deployment.ip }}:{{ deployment.port }}"
        ServiceUrl: "http://{{ deployment.ip }}:{{ deployment.port }}"

services:
  direct:
    ip: 10.0.0.1
    port: 8080

hosts:
  - domain: "example.com"
    www_redirect: true
    paths:
      - path: "/test"
        deployments:
          blue:
            service_name: redirector
            weight: 50
          green:
            ip: 10.0.0.2
            port: 8080
            weight: 50
        middlewares:
          - enable-headers
          - forward-server

    # Root path (catch-all)
    deployments:
      catch-all:
        ip: 10.0.0.1
        port: 8080
        weight: 100
