etcd:
  endpoints: ["https://etcd:2379"]
  timeout: 2000
  keep_alive: 300
  tls:
    cert: "./config/tls/etcd-peer.pem"
    key: "./config/tls/etcd-peer-key.pem"
    ca: "./config/tls/ca.pem"
    domain: etcd

middlewares:
  enable-headers:
    headers:
      custom_request_headers:
        X-Forwarded-Proto: "https"
        X-Forwarded-Port: "443"
        Location: ""
      custom_response_headers:
        Location: ""
      access_control_allow_methods:
        - "GET"
      access_control_allow_headers:
        - "Content-Type"
      access_control_expose_headers:
        - Location
      add_vary_header: true

hosts:
  - domain: ari.io
    paths:
      - path: "/test"
        deployments:
          blue:
            ip: google.com
            port: 443
            weight: 50
          green:
            ip: yahoo.com
            port: 443
            weight: 50
        middlewares:
          - enable-headers
          - forward-server

    # Root path (catch-all)
    deployments:
      ari-dot-io:
        ip: google.com
        port: 443
        weight: 99
      other:
        ip: google.com
        port: 1234
        weight: 1
        protocol: tcp
