etcd:
  endpoints: ["https://0.0.0.0:2379"]
  timeout: 2000
  keep_alive: 300
  tls:
    cert: "./config/tls/etcd-peer.pem"
    key: "./config/tls/etcd-peer-key.pem"
    ca: "./config/tls/ca.pem"
    domain: herringbank.com

middlewares:
  enable-headers:
    headers:
      custom_request_headers:
        X-Forwarded-Proto: "https"
        X-Forwarded-Port: "443"
        Location: ""
      custom_response_headers:
        Location: ""
      access_control_allow_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      access_control_allow_headers:
        - "Content-Type"
        - Content-Length
        - Accept-Encoding
        - X-CSRF-Token
        - Authorization
        - accept
        - origin
        - Cache-Control
        - X-Requested-With
        - Host
        - "Location"
      access_control_expose_headers:
        - Location
      add_vary_header: true

  forward-server:
    headers:
      custom_request_headers:
        X-Forwarded-Proto: "https"
        X-Forwarded-Port: "443"
        Location: ""
        X-Forwarded-Server: "traefik"

  add-www:
    headers:
      custom_request_headers:
        X-Forwarded-Proto: "https"
        X-Forwarded-Port: "443"
        Location: ""

hosts:
  - domain: "ibs.collegegreen.net"
    pass_through: true
    www_redirect: true
    paths:
      - path: "/premier-pay-tools"
        deployments:
          blue:
            ip: redirector
            port: 3000
            weight: 100
        middlewares:
          - enable-headers
          - forward-server
        strip_prefix: true

    # Root path (catch-all)
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100
    middlewares:
      - enable-headers
      - forward-server
  - domain: www.collegegreen.net
    pass_through: true
    www_redirect: true
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100

  - domain: ibs.financialpayments.com
    pass_through: true
    www_redirect: false
    paths:
      - path: /rails-sso
        deployments:
          blue:
            ip: redirector
            port: 3000
            weight: 100
        middlewares:
          - enable-headers
          - forward-server
        strip_prefix: true
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100

  - domain: www.financepayments.com
    pass_through: true
    www_redirect: true
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100

  - domain: static.financialpayments.com
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100

  - domain: campus-commerce.collegegreen.net
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100

  - domain: billing.financialpayments.com
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100

  - domain: api.financialpayments.com
    deployments:
      blue:
        ip: redirector
        port: 3000
        weight: 100
