etcd:
  endpoints: ["https://etcd:2379"]
  timeout: 2000
  keep_alive: 300
hosts:
  - domain: "ari.io"
    pass_through: true
    www_redirect: false
    paths:
      - path: /rails-sso
        deployments:
          green-with-cookie: &green-with-cookie
            ip: 10.8.92.2
            port: 3002
            weight: 0
            with_cookie:
              name: "green"
              value: "true"
          blue: &blue
            ip: redirector
            port: 3000
            weight: 100
        middlewares:
          - enable-headers
          - forward-server
        strip_prefix: true
    deployments:
      catch-all:
        ip: redirector
        port: 3000
        weight: 100
