etcd:
  endpoints: ["https://etcd:2379"]
  timeout: 2000
  keep_alive: 300
  tls:
    cert: "./config/tls/traefik.pem"
    key: "./config/tls/traefik-key.pem"
    ca: "./config/tls/ca.pem"
    domain: etcd

services:
  redirector:
    ip: redirector
    port: 3000

hosts:
  - domain: "ari.io"
    pass_through: true
    www_redirect: false
    paths:
      - path: /api
        deployments:
          green-with-cookie:
            ip: "10.8.92.2"
            port: 3002
            weight: 100
            with_cookie:
              name: "green"
              value: true
        middlewares:
          - enable-headers
        strip_prefix: true
    deployments:
      catch-all:
        service_name: redirector
        weight: 100
