http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          server: ""
          x-powered-by: "Your host"

    traefikAuth:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd

    redirect-handler:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Location: ""

    default-redirect-middleware:
      redirectRegex:
        regex: "^https?://(.+)"
        replacement: "https://example.com"
        permanent: true

    handle-service-redirect-middleware:
      redirectRegex:
        regex: "^(https?://)(.*)/(.*)$"
        replacement: "${1}/${2}/${3}"
        permanent: true

    default-ratelimit:
      rateLimit:
        average: 100
        burst: 20
        period: "1m"

    default-auth:
      chain:
        middlewares:
          - traefikAuth
          - default-headers

    redirector-auth:
      forwardAuth:
        address: "http://redirector:3000"
        trustForwardHeader: true
        authResponseHeaders:
          - "ServiceAddr"
          - "ServiceUrl"
          - "X-Forwarded-Host"
          - "X-Forwarded-Uri"
          - "X-Forwarded-Method"
          - "X-Forwarded-Proto"
          - "X-Real-Ip"
        authResponseHeadersRegex: "^X-.*"

    default:
      chain:
        middlewares:
          - default-headers

    prometheus-service:
      loadBalancer:
        servers:
          - port: 9090
    grafana-service:
      loadBalancer:
        servers:
          - port: 3000
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false # Allow requests without SNI
  certificates:
    - certFile: /etc/traefik/tls/server.pem
      keyFile: /etc/traefik/tls/server-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/tls/server.pem
        keyFile: /etc/traefik/tls/server-key.pem
