api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        domains:
          - main: "ari.io"
            sans: ["*.ari.io", "localhost"]
          - main: "example.com"
            sans: ["localhost", "*.example.com"]
  metrics:
    address: ":8899"

  # dashboard:
  #   address: ":8081"

providers:
  etcd:
    endpoints:
      - "etcd:2379"
    rootKey: "traefik"
    tls:
      cert: /etc/traefik/etcd-client.pem
      key: /etc/traefik/etcd-client-key.pem
      ca: /etc/traefik/ca.pem
  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true

log:
  level: DEBUG
  format: json

accessLog:
  filePath: "/dev/stdout"
  format: json
  fields:
    headers:
      defaultMode: keep
      names:
        Host: keep
        X-Forwarded-For: keep
        X-Forwarded-Proto: keep
        X-Real-IP: keep
    names:
      StartUTC: keep
      StartLocal: keep
      Duration: keep
      RetryAttempts: keep
      RouterName: keep

tracing:
  addInternals: true
  serviceName: traefik

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addrouterslabels: false
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Plugins
# Static configuration for plugins

# experimental:
#   plugins:
#     session-max-age:
#       moduleName: github.com/longbridgeapp/traefik-session-max-age
#       version: v0.1.0
#     traefik-plugin-proxy-cookie:
#       moduleName: github.com/SchmitzDan/traefik-plugin-proxy-cookie
#       version: v0.0.2
#     traefik-cookie-handler-plugin:
#       moduleName: github.com/vaspapadopoulos/traefik-cookie-handler-plugin
#       version: v0.1.0
